### ISSUE TITLE
responsibleとaccountable

### ISSUE THREAD

**Issue by wsfjp** [kdmsnr/NexusGuide#1]
responsibleが「実行責任」というのはしっくりくるが、accountableが「説明責任」というのは、一般的には正しい訳だが、違和感が強い。
ググっても「説明責任」という訳は変という解説が多く出てくる。
思いついたのは
「最終責任」、「結果責任」、単に「責任」

**Comment by kdmsnr** [comment]
XP本では定訳なので諦めました

**Comment by kdmsnr** [comment]
Macの辞書だと ``required or expected to justify actions or decisions`` と出ます。justify は「説明」でも大きく離れていなさそう。

**Comment by kdmsnr** [comment]
``単に「責任」``はナシ（対比ができない）。最終〜と結果〜は、候補としてはOKです。

**Comment by wsfjp** [comment]
私の希望は、結果〜、最終〜、説明〜という順です。
正しいのが「説明」というのは理解した上で、「結果」にしたい。
でも定訳だから「説明」にするというのもそれはそれで納得です。

**Comment by kdmsnr** [comment]
結果〜でもいいと思います。お任せします。

**Comment by wsfjp** [comment]
文章を置換して、何度か眺めてみました。
統合インクリメントは、結果責任にしたい（２か所）
プロダクトバックログは、最終責任にしたい（２か所）
訳を統一するなら、嫌いだけど説明責任なのか

**Comment by kdmsnr** [comment]
何にするかはさておき、統一したほうがよいと思います。

**Comment by wsfjp** [comment]
>The Product Owner may do the above work, or have the Development Team do it. However, the Product Owner remains accountable.
>上記の作業は、プロダクトオーナーが行う場合もあれば、開発チームが行う場合もある。いず れの場合も、最終的な責任はプロダクトオーナーが持つ。

スクラムガイドで「最終的な責任」となっていて、最終責任、結果責任よりも若干違和感が軽減される気がするので、「最終的な責任」としようと思うのですが、どうでしょう？

**Comment by kdmsnr** [comment]
よいと思います
