### ISSUE TITLE
Requirements 要件 要求

### ISSUE THREAD

**Issue by wsfjp** [kdmsnr/NexusGuide#2]
英語では、Requirementsですが、日本語には要件と要求があります。
明確な定義はないですが、要件には、UIや実装方法を含んでいて、ユーザーの真の要求は欠落していて、典型的には、WFの仕様書を書く前に書くもの。交渉不可能な物という印象があります。
要求はユーザーストーリーに代表されるような、ユーザーの真の要求を表す物という印象があります。
なので、できれば要件ではなくて、要求という言葉を使いたいです。

**Comment by kdmsnr** [comment]
業界用語的には「要求」というのはないんですよねえ。

```
  Requirement                           要件    itil
  Service Level Requirement (SLR)       サービスレベル要件（SLR）       itil
  functional requirement                機能要件        jstqb
  non-functional requirement            非機能要件      jstqb
  requirement                           要件    jstqb
  test requirement                      テスト要件      jstqb
```

**Comment by kdmsnr** [comment]
PMBOKは「要求」でした。

**Comment by wsfjp** [comment]
個人の意見ですが、アジャイル以前のソフトウエア業界用語から離れたい
あと「アジャイルソフトウエア要求」って本があったような
あれが「アジャイルソフトウエア要件」だったら嫌だなと、、、

**Comment by wsfjp** [comment]
ユーザーストーリー的な文脈で要求という言葉が多く使われ
事前に仕様を決める開発で真のニーズが不明な文脈で要件という言葉が使われる傾向はあると思っています。
極めて曖昧な話ではありますが、、、

**Comment by kdmsnr** [comment]
スクラムガイドで「要求」にしていたので合わせますかねえ。
とはいえ「要求のスコープ」とかだいぶ気持ち悪いんですけども。

**Comment by wsfjp** [comment]
「要求のスコープ」は気持ち悪いですが、「要件のスコープ」でも、気持ち悪さはそんなに変わらないと感じます。
PMで使う場合の専門用語としてのスコープには、要求、要件、仕様、機能という意味が含まれているので、「要求のスコープ」ではなくて、単に「スコープ」ではダメでしょうか？

**Comment by kdmsnr** [comment]
単にスコープはダメですね（原文と違う）。ググったら、BABOKっぽいところでは使われてるみたいなので、大丈夫ですかねえ。
