### ISSUE TITLE
Sprint Planning meeting

### ISSUE THREAD

**Issue by wsfjp** [kdmsnr/NexusGuide#4]
スクラムガイドで、「スプリントプランニング」で統一しているのに、原文にSprint Planning とSprint Planning meetingの両方が出てきて、今は「スプリントプランニングミーティング」と原文に忠実に訳している。
本当は「スプリントプランニング」で統一したい。
Nexusスプリントプランニングミーティングに関しては、原文に忠実にというのが優先される気もするが、スクラムのミーティングをスプリントプランニングミーティングとするのは誤記と考えることもできる気もする。
リファインメントに関しては、スクラムガイドでミーティングではない感じで定義されているので、「リファインメントミーティング」は良いと思う。

**Comment by kdmsnr** [comment]
ミーティングなしの統一でよいと思います

**Comment by wsfjp** [comment]
リファインメントも含めてでしょうか？
リファインメントに関しては逆に、ミーティングだということがわからなくなるという心配もしたのですが。（取るべきじゃないという強い意見でもないです）

**Comment by wsfjp** [comment]
とりあえず、Nexusスプリントプランニング、スプリントプランニングは、ミーティングを取るで統一しました。
7c946ecf582e1f47c8c2774d6a86acd669b858db

**Comment by kdmsnr** [comment]
$B%j%U%!%$%s%a%s%H$N%_!<%F%#%s%0$K$9$k$H$+(B

**Comment by kdmsnr** [comment]
リファインメントのミーティングにするとか
